apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: practical-elgamal
        image: moctader/my-grpc-server:latest
        ports:
        - containerPort: 50051
